// Generated by https://quicktype.io
export interface ListImageInterface {
  data: ImageInterface[];
}

export interface ImageInterface {
  albumId: number;
  id: number;
  title: string;
  url: string;
  thumbnailUrl: string;
}
